version: '3'
services:
  instantaneousgram-user:
    build: 
      context: ./InstantaneousGram-Users
      dockerfile: Dockerfile
    image: slothh/instantaneousgram/instantaneousgram-user:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development

  instantaneousgram-login:
    build: 
      context: ./InstantaneousGram-Login
      dockerfile: Dockerfile
    image: slothh/instantaneousgram/instantaneousgram-login:latest
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development