version: '3'
services:
  instantaneousgram-user:
    build: 
      context: ./InstantaneousGram-UserPorifile
      dockerfile: Dockerfile
    image: slothh/instantaneousgram-UserProfileServices:latest
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development

  instantaneousgram-Authentication:
    build: 
      context: ./InstantaneousGram-Authentication
      dockerfile: Dockerfile
    image: slothh/instantaneousgram-AuthenticationServices:latest
    ports:
      - "5002:80"
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ASPNETCORE_ENVIRONMENT=Development