apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: instantaneousgram-imageandvideoprocessing-hpa
  namespace: instantaneousgram
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: instantaneousgram-imageandvideoprocessing
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
