apiVersion: apps/v1
kind: Deployment
metadata:
  name: instantaneousgram-likeandcomment
  namespace: instantaneousgram
spec:
  replicas: 3
  selector:
    matchLabels:
      app: instantaneousgram-likeandcomment
  template:
    metadata:
      labels:
        app: instantaneousgram-likeandcomment
    spec:
      containers:
      - name: instantaneousgram-likeandcomment
        image: slothh/instantaneousgram-likeandcommentservices:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: RabbitMQ__HostName
          value: "rabbitmq"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__UserName
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: rabbitmq-username
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: rabbitmq-password
        - name: Auth0__ClientId
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: auth0-client-id
        - name: Auth0__ClientSecret
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: auth0-client-secret
        - name: Auth0__ApiAudience
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: auth0-api-audience
        - name: Auth0__Domain
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: auth0-domain
        - name: ConnectionString  # Environment variable name in your application
          valueFrom:
            secretKeyRef:
              name: db-connection   # Name of the Secret
              key: connectionString  # Key within the Secret              
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 250m
            memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: instantaneousgram-likeandcomment
  namespace: instantaneousgram
spec:
  type: LoadBalancer
  selector:
    app: instantaneousgram-likeandcomment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
