apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-gateway-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "50m"
    kubernetes.io/ingress.ClassName: "nginx"
spec:
  tls:
  - hosts:
    - instantaneousgram.ddns.net
    secretName: tls-secret # Optional: if you have an SSL certificate
  rules:
  - host: instantaneousgram.ddns.net
    http:
      paths:
      - path: /users
        pathType: Prefix
        backend:
          service:
            name: userservice
            port:
              number: 80
      - path: /userprofiles
        pathType: Prefix
        backend:
          service:
            name: userprofileservice
            port:
              number: 80
      - path: /test
        pathType: Prefix
        backend:
          service:
            name: testservice
            port:
              number: 80
      - path: /weatherforecast
        pathType: Prefix
        backend:
          service:
            name: weatherforecastservice
            port:
              number: 80
