apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: instantaneousgram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management-alpine
        ports:
        - containerPort: 5672
        - containerPort: 15672
        volumeMounts:
        - name: rabbitmq-data
          mountPath: /var/lib/rabbitmq
        - name: rabbitmq-log
          mountPath: /var/log/rabbitmq
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      volumes:
      - name: rabbitmq-data
        hostPath:
          path: /data/rabbitmq
      - name: rabbitmq-log
        hostPath:
          path: /log/rabbitmq

---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-clusterip
  namespace: instantaneousgram
spec:
  type: ClusterIP
  selector:
    app: rabbitmq
  ports:
  - name: amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: management
    protocol: TCP
    port: 15672
    targetPort: 15672