apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: instantaneousgram-ingress
  namespace: instantaneousgram
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: instantaneousgram.ddns.net
      http:
        paths:
          - path: /userprofile(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: instantaneousgram-userprofile-clusterip
                port:
                  number: 80
          - path: /authentication(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: instantaneousgram-authentication-clusterip
                port:
                  number: 80
          - path: /contentmanagement(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: instantaneousgram-contentmanagement-clusterip
                port:
                  number: 80
          - path: /imageandvideoprocessing(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: instantaneousgram-imageandvideoprocessing-clusterip
                port:
                  number: 80
          - path: /likeandcomment(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: instantaneousgram-likeandcomment-clusterip
                port:
                  number: 80
