apiVersion: apps/v1
kind: Deployment
metadata:
  name: instantaneousgram-userprofile
  namespace: instantaneousgram
spec:
  replicas: 3
  selector:
    matchLabels:
      app: instantaneousgram-userprofile
  template:
    metadata:
      labels:
        app: instantaneousgram-userprofile
    spec:
      dnsConfig:
        searches:
          - instantaneousgram.svc.cluster.local
          - svc.cluster.local
          - cluster.local
      containers:
      - name: instantaneousgram-userprofile
        image: slothh/instantaneousgram-userprofileservices:latest
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: RabbitMQ__HostName
          value: "rabbitmq-clusterip.instantaneousgram.svc.cluster.local"
        - name: RabbitMQ__Port
          value: "5672"
        - name: RabbitMQ__UserName
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: rabbitmq-username
        - name: RabbitMQ__Password
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: rabbitmq-password
        - name: Auth0__ClientId
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: auth0-client-id
        - name: Auth0__ClientSecret
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: auth0-client-secret
        - name: Auth0__ApiAudience
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: auth0-api-audience
        - name: Auth0__Domain
          valueFrom:
            secretKeyRef:
              name: rabbitmq-auth0-credentials
              key: auth0-domain
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: instantaneousgram-userprofile-clusterip
  namespace: instantaneousgram
spec:
  type: ClusterIP
  selector:
    app: instantaneousgram-userprofile
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
