apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-auth0-credentials
  namespace: instantaneousgram
type: Opaque
data:
  rabbitmq-username: dXNlcg==
  #dXNlcg==  
  rabbitmq-password: bEprNXQxRkdJZHRtY2M4MQ==
  #Nzl6NGVXVDJKRkU3NzNDVw==
  auth0-client-id: dWUxTXc3dFNsYmlPS1NLYVpyVWhwYVhPd0NtbzJVTGk=
  auth0-client-secret: RXg4bXByQ05oa1FIQ2xoUS1MLUcwUU5Ka3NZZDhwa2ZYZTVtVWhaRk5YNzFQX0c1QzVnd1dSY1JpSzA0czN0dg==
  auth0-api-audience: aHR0cHM6Ly9kZXYtZG5vaGZ6cXZqbDdpZnVsZi51cy5hdXRoMC5jb20vYXBpL3YyLw==
  auth0-domain: ZGV2LWRub2hmenF2amw3aWZ1bGYudXMuYXV0aDAuY29t
