apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-data
  namespace: instantaneousgram
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-log
  namespace: instantaneousgram
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
