name: CI/CD Workflow

on:
  push:
    branches: [ main, Development, CI/CD ]
  pull_request:
    branches: [ main, Development, CI/CD ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        microservice: 
          - InstantaneousGram-Authentication
          - InstantaneousGram-UserProfile
          - InstantaneousGram-ApiGateway
          - InstantaneousGram-ContentManagement
          - InstantaneousGram-ImageAndVideoProcessing
          - InstantaneousGram-LikeAndComment

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 7.0  # adjust this to your .NET Core version

      - name: Cache .NET packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
          restore-keys: |
            ${{ runner.os }}-nuget-

      - name: Install dependencies
        run: dotnet restore ${{ matrix.microservice }}

      - name: Build
        run: dotnet build ${{ matrix.microservice }} --configuration Release --no-restore

      - name: Test
        run: dotnet test ${{ matrix.microservice }} --no-restore --verbosity normal
